# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('alias', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('birthday', models.DateField(default=None, max_length=111)),
                ('password', models.CharField(max_length=111)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotes', models.ManyToManyField(related_name='_user_quotes_+', to='login_app.User')),
            ],
        ),
    ]
